version: "2"
services:
  bamboo:
    image: clodoaldosanchez/bamboo:6.10.3
    volumes:
      - /home/csanchez/docker/bamboo/bamboo_home:/var/atlassian/application-data/bamboo
    ports:
      - "8085:8085"


