version: "2"
services:
  nexus3:
    image: clodoaldosanchez/nexus3:3.1.0
    ports:
    - 8082:8082
    volumes:
      - 'D:/dev/nexus-conf/nexus-default.properties:/opt/sonatype/nexus/etc/nexus-default.properties'
      - 'D:/dev/nexus-data:/nexus-data'
