version: '2'
services:
  wls12c:
    image: clodoaldosanchez/weblogic:12.2.1.3-developer
    environment:
      - TZ=America/Lima
      - ADMIN_NAME=AdminServer
      - ADMIN_LISTEN_PORT=7002
      - DOMAIN_NAME=base_domain
      - ADMINISTRATION_PORT_ENABLED=false
      - ADMINISTRATION_PORT=9002
    ports:
      - "7002:7002"
    volumes:
      - D:/work/docker/wls12:/u01/oracle/properties
      - D:/work/docker/wls12/domains/base_domain:/u01/oracle/user_projects/domains/base_domain:rw
      - D:/logs:/logs:rw
